trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Disparando GitHub Actions desde Azure DevOps..."
      curl -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $(GITHUB_TOKEN)" \
        https://api.github.com/repos/ezesagardia00/Test-DevAzure/actions/workflows/ci.yml/dispatches \
        -d '{"ref":"main"}'
    displayName: 'Disparar GitHub Actions'
